export const GET_TODO_LISTS_REQUEST="GET_TODO_LISTS_REQUEST";
export const GET_TODO_LISTS_SUCCESS="GET_TODO_LISTS_SUCCESS";
export const GET_TODO_LISTS_FAILURE="GET_TODO_LISTS_FAILURE";


export const ADD_TODO_LISTS_REQUEST="ADD_TODO_LISTS_REQUEST";
export const ADD_TODO_LISTS_SUCCESS="ADD_TODO_LISTS_SUCCESS";
export const ADD_TODO_LISTS_FAILURE="ADD_TODO_LISTS_FAILURE";

export const TOGGLE_TODO_LISTS_REQUEST="TOGGLE_TODO_LISTS_REQUEST";
export const TOGGLE_TODO_LISTS_SUCCESS="TOGGLE_TODO_LISTS_SUCCESS";
export const TOGGLE_TODO_LISTS_FAILURE="TOGGLE_TODO_LISTS_FAILURE";

export const REMOVE_TODO_LISTS_REQUEST="REMOVE_TODO_LISTS_REQUEST";
export const REMOVE_TODO_LISTS_SUCCESS="REMOVE_TODO_LISTS_SUCCESS";
export const REMOVE_TODO_LISTS_FAILURE="REMOVE_TODO_LISTS_FAILURE";


